2021-06-20 15:59:37.399 [main] ERROR traning.task04.service.creator.WheelCreator - The method is exception, non-existent dimensions
2021-06-20 16:02:38.399 [main] ERROR traning.task04.service.creator.WheelCreator - The method is exception, non-existent dimensions
2021-06-20 16:04:54.952 [main] ERROR traning.task04.service.creator.WheelCreator - The method is exception, non-existent dimensions
2021-06-20 16:04:54.959 [main] ERROR traning.task04.service.creator.WheelCreator - The method is exception, non-existent dimensions
2021-06-20 16:04:54.962 [main] ERROR traning.task04.service.creator.WheelCreator - The method is exception, non-existent dimensions
2021-06-20 16:05:20.254 [main] ERROR traning.task04.service.creator.WheelCreator - The method is exception, non-existent dimensions
2021-06-20 16:05:20.275 [main] ERROR traning.task04.service.creator.WheelCreator - The method is exception, non-existent dimensions
2021-06-20 16:05:20.277 [main] ERROR traning.task04.service.creator.WheelCreator - The method is exception, non-existent dimensions
2021-06-20 16:05:26.255 [main] ERROR traning.task04.service.creator.WheelCreator - The method is exception, non-existent dimensions
2021-06-20 16:05:26.262 [main] ERROR traning.task04.service.creator.WheelCreator - The method is exception, non-existent dimensions
2021-06-20 17:03:31.734 [main] ERROR traning.task04.dao.impl.FileCarDAO - The method is exception.The file src\main\resources\cars.txt did not read
2021-06-20 17:03:31.738 [main] ERROR traning.task04.service.impl.CarServiceImpl - Error during reading
by.traning.task04.dao.exception.DAOException: The file did not read
	at by.traning.task04.dao.impl.FileCarDAO.read(FileCarDAO.java:28) ~[classes/:?]
	at by.traning.task04.service.impl.CarServiceImpl.all(CarServiceImpl.java:126) ~[classes/:?]
	at by.traning.task04.service.impl.CarServiceImplTest.allTest(CarServiceImplTest.java:43) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: java.nio.file.NoSuchFileException: src\main\resources\cars.txt
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:375) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:426) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420) ~[?:?]
	at java.nio.file.Files.newInputStream(Files.java:160) ~[?:?]
	at java.nio.file.Files.newBufferedReader(Files.java:2916) ~[?:?]
	at java.nio.file.Files.readAllLines(Files.java:3396) ~[?:?]
	at java.nio.file.Files.readAllLines(Files.java:3436) ~[?:?]
	at by.traning.task04.dao.impl.FileCarDAO.read(FileCarDAO.java:25) ~[classes/:?]
	... 29 more
2021-06-20 17:23:05.567 [main] ERROR traning.task04.service.impl.CarServiceImpl - Error during found
2021-06-20 17:26:52.643 [main] ERROR traning.task04.service.impl.CarServiceImpl - Error during found
2021-06-20 17:27:31.053 [main] ERROR traning.task04.service.impl.CarServiceImpl - Error during found
2021-06-20 17:53:54.972 [main] ERROR traning.task04.service.impl.CarServiceImpl - Error during found
2021-06-20 17:56:04.340 [main] ERROR by.traning.task04.controller.CommandProvider - The method is exception, wrong request
2021-06-20 18:12:34.199 [main] ERROR traning.task04.service.impl.CarServiceImpl - Error during found
2021-06-20 18:12:34.202 [main] ERROR traning.task04.controller.impl.CarRun - The method is exception, error during the procedure
by.traning.task04.service.exception.ServiceException: Error during found
	at by.traning.task04.service.impl.CarServiceImpl.findCar(CarServiceImpl.java:79) ~[classes/:?]
	at by.traning.task04.service.impl.CarServiceImpl.run(CarServiceImpl.java:89) ~[classes/:?]
	at by.traning.task04.controller.impl.CarRun.execute(CarRun.java:24) [classes/:?]
	at by.traning.task04.controller.Controller.executeTask(Controller.java:29) [classes/:?]
	at by.traning.task04.Runnable.main(Runnable.java:23) [classes/:?]
2021-06-20 18:12:44.974 [main] ERROR traning.task04.service.impl.CarServiceImpl - Error during found
2021-06-20 18:12:44.974 [main] ERROR traning.task04.controller.impl.CarRun - The method is exception, error during the procedure
by.traning.task04.service.exception.ServiceException: Error during found
	at by.traning.task04.service.impl.CarServiceImpl.findCar(CarServiceImpl.java:79) ~[classes/:?]
	at by.traning.task04.service.impl.CarServiceImpl.run(CarServiceImpl.java:89) ~[classes/:?]
	at by.traning.task04.controller.impl.CarRun.execute(CarRun.java:24) [classes/:?]
	at by.traning.task04.controller.Controller.executeTask(Controller.java:29) [classes/:?]
	at by.traning.task04.Runnable.main(Runnable.java:23) [classes/:?]
2021-06-20 18:13:00.807 [main] ERROR traning.task04.service.impl.CarServiceImpl - Error during found
2021-06-20 18:13:00.807 [main] ERROR traning.task04.controller.impl.CarNameReceive - The method is exception, error during the procedure
by.traning.task04.service.exception.ServiceException: Error during found
	at by.traning.task04.service.impl.CarServiceImpl.findCar(CarServiceImpl.java:79) ~[classes/:?]
	at by.traning.task04.service.impl.CarServiceImpl.nameReceive(CarServiceImpl.java:97) ~[classes/:?]
	at by.traning.task04.controller.impl.CarNameReceive.execute(CarNameReceive.java:24) [classes/:?]
	at by.traning.task04.controller.Controller.executeTask(Controller.java:29) [classes/:?]
	at by.traning.task04.Runnable.main(Runnable.java:23) [classes/:?]
2021-06-20 18:15:15.941 [main] ERROR traning.task04.service.impl.CarServiceImpl - Error during found
2021-06-20 18:15:15.945 [main] ERROR traning.task04.controller.impl.CarRun - The method is exception, error during the procedure
by.traning.task04.service.exception.ServiceException: Error during found
	at by.traning.task04.service.impl.CarServiceImpl.findCar(CarServiceImpl.java:79) ~[classes/:?]
	at by.traning.task04.service.impl.CarServiceImpl.run(CarServiceImpl.java:89) ~[classes/:?]
	at by.traning.task04.controller.impl.CarRun.execute(CarRun.java:24) [classes/:?]
	at by.traning.task04.controller.Controller.executeTask(Controller.java:29) [classes/:?]
	at by.traning.task04.Runnable.main(Runnable.java:23) [classes/:?]
